<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/password/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Out of Office plugin       |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/
$labels['out_of_office']  = 'Automatická odpověď';
$labels['oooactivate']  = 'Aktivní:';
$labels['ooosubject']  = 'Předmět automatické odpovědi:';
$labels['ooobody']  = 'Text automatické odpovědi:';
$messages['internalerror']  = 'Při běhu pluginu "Automatická odpověď" nastala chyba';
$messages['configerror']  = 'Chyba konfigurace pluginu "Automatická odpověď"';
$messages['noooosubject'] = "Předmět nesmí být prázdný";
$messages['noooobody'] = "Text odpovědi nesmí být prázdný";
