<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/password/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Out of Office plugin       |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/
$labels['out_of_office']  = 'Out of Office';
$labels['oooactivate']  = 'Enabled:';
$labels['ooosubject']  = 'Subject:';
$labels['ooobody']  = 'Message:';
$messages['internalerror']  = 'Could not save Out of office message.';
$messages['configerror']  = 'Out of office plugin is misconfigured.';
$messages['noooosubject'] = "Please input subject";
$messages['noooobody'] = "Please input body message";
